static_analyses:
  ignore_files:
    - obj_tables_test_migration_repo/migrations/bad_custom_io_classes.py
  ignore_unused_requirements: []
  ignore_missing_requirements:
    - configobj
downstream_dependencies:
  - obj_tables
email_notifications: []